[0.3.0] Club Data Models
suankularb-wittayalai-school/mysk-api pull request #21
Opened 2024-05-28 14:59 UTC by Galax028

I have implemented the necessary data models for club functionality. This resolves BACK-65.

> [!NOTE]
> The data model is not queryable nor sortable yet, but the boilerplate is already in place in case someone wants to start working on that. It's good for now, but we'll add it if needed.

2024-05-28 15:05 UTC, smartwhatt requested changes
Few changes

2024-05-28 16:08 UTC, Galax028 commented on mysk-lib/src/models/club/db.rs
> +#[base_query(query = "SELECT * FROM organizations")]
My bad, I was copying much boilerplate around :skull:

2024-05-29 01:13 UTC, smartwhatt approved these changes
LGTM!!

2024-05-29 01:30 UTC, owo93 approved these changes
LGTM 😦

2024-05-29 02:29 UTC, merged